// <auto-generated />
namespace FishMarket.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fish : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fish));
        
        string IMigrationMetadata.Id
        {
            get { return "201803231246520_Fish"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
